# Generated by Django 4.1.7 on 2023-03-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_comments_like_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.EmailField(default='sanidhya738@gmail.com', max_length=254),
        ),
    ]
